### ISSUE TITLE
Access Control copy edits

### ISSUE THREAD

**Issue by peries** [Robo3D/roboOctoprint#13]
@victorevector @AllenMcAfee for your review

![1 copy](https://user-images.githubusercontent.com/24902256/33046452-db8b2bd8-ce05-11e7-8a5d-94cf609739ef.PNG)

**dev notes by victor**
This text can be found in `src/octoprint/templates/dialogs/wizard/firstrun_start.jinja2`

![2 copy](https://user-images.githubusercontent.com/24902256/33104767-a5623dec-cede-11e7-83bc-afc120078872.PNG)

**dev notes by victor**
This text can be found in `src/octoprint/plugins/corewizard/templates/corewizard_acl_wizard.jinja2`

**dev notes by victor**
Re: the html elements that are crossed out... The wizard dialog box is defined in the file `src/octoprint/templates/dialogs/wizard.jinja2`. Here are some (not all) options on how to edit them out. 

- select html identifier and append a `display: none;` css rule.

- create "minimal" flag and code roboOctoprint to react to this flag; i.e. roboOctoprint chooses which wizard template to render depending on flag. 

Relevant elements:

1. side bar: 
    1. div#wizard_dialog_menu { display: none;}
    1. div.span3 --> div.span11

2. previous button:
    1. div.modal-footer button.button-previous { display: none; }

3. footer text:
    1. div.modal-footer div.text-center { display: none; }

4. next text:
    1. div.modal-footer button.button-next
    1. use reactive html or js to change the text value based on modal content or button event.

**Comment by peries** [comment]
@mnacinopa and I haven't been able to figure out how to properly disable it. Could one of you show us?

**Comment by victorevector** [comment]
## Internal notes 

- how to reset password: https://github.com/foosel/OctoPrint/issues/1063

**Comment by victorevector** [comment]
## SSH info

- An advanced user wants to enable SSH (default: disabled).

- A user wants to know the implications of turning it on.
    - Any remote user with the printer's username and password can control the printer. 

- A user wants to know the default password.
     - username: pi password: <printer-name>

- A user wants to know how to change the default password. 
    - https://www.raspberrypi.org/documentation/linux/usage/users.md

**Comment by peries** [comment]
@victorevector @AllenMcAfee 
![hello](https://user-images.githubusercontent.com/24902256/33350561-489bc49a-d454-11e7-8386-18aaf2377e69.png)
_________________________
![access control](https://user-images.githubusercontent.com/24902256/33350565-4cad79f2-d454-11e7-9c28-1548bdc0d7ce.png)
_________________________
![ssh control](https://user-images.githubusercontent.com/24902256/33350845-ccc17d18-d455-11e7-8f90-853090e16a9e.png)
_________________________
![setup complete](https://user-images.githubusercontent.com/24902256/33350782-7ee86818-d455-11e7-91d9-8e4052fe8be9.png)

**Comment by peries** [comment]
and then if they've already created an account,
![access control 1](https://user-images.githubusercontent.com/24902256/33350614-9615b212-d454-11e7-82d9-1b59f1d27a80.png)

**Comment by peries** [comment]
This is just an idea for new styling, although this content can be fitted into the current styling just fine. I can also send you the text in another document so you can copy/paste

**Comment by peries** [comment]
@victorevector questions

1. can the 'access control' screens be dynamic such that it knows if you've created an admin account already?
2. can the 'setup complete' screen be dynamic such that it shows which selections you've just made (so you can confirm) before finishing the wizard?

**Comment by victorevector** [comment]
@peries 

re: https://github.com/Robo3D/roboOctoprint/issues/13#issuecomment-347709584

1. The setup wizard does display a different interface if an admin account has already been registered.

2. I can carry over the values to the end screen. It does raise questions about "confirmation". Once you enable access control you can't undo it. Another thing, I think the surest way to reset an admin password is to reflash the whole OS.

**Comment by mnacinopa** [comment]
@peries 
The only things to edit
- [x] The default username is actually pi, I think?
- [x] At the Enable/Disable Screens we need to warn them this will restart their printer and interrupt any print jobs going on

**Comment by mnacinopa** [comment]
@victorevector 
When there are multiple user accounts can only the admin acc enable/disable access control & ssh?

**Comment by peries** [comment]
@victorevector feedback for the latest version

Within the wizard, 
## Start
- [x] second paragraph copy edit: If you're a new user, we'd like to welcome you to the Robo family! If you've been here before, we'll take you through some newly added settings.
- [ ] delete previous button
- [x] delete 'unless otherwise noted..." line
- [ ] change next button text to 'start'

## Access Control
- [ ] Note copy edit: **NOTE:** If you lose your new password, you will need to contact Robo customer support. In which case, you risk losing all of the data on your printer.
- [ ] delete previous button
- [x] delete 'unless otherwise noted..." line

## SSH Control
- [x] Change sidebar to say 'SSH Control' instead of wizard
- [x] Change title to say 'SSH Control' 
- [x] Delete apostrophe in it's
- [x] Delete extra space after einstein
- [x] Add period after closed parentheses
- [x] Copy edit to the last line of the last paragraph: If you keep SSH disabled, there is no need to change your password.
- [x] delete 'unless otherwise noted..." line
- [x] change previous button text to 'go back'

## Finish
- [x] delete 'unless otherwise noted..." line
- [x] change previous button text to 'go back'

**Comment by peries** [comment]
## Enabling
![capture000](https://user-images.githubusercontent.com/24902256/33970770-c11a2d2c-e029-11e7-803e-16e112bf6284.PNG)

Title: Enable Security Features
Body: You are about to launch the setup wizard to enable remote access security features. You will have to complete the wizard in order to continue using the web dashboard. The dashboard and your printer will automatically restart once the wizard is finished. This will disrupt any active prints.

Are you sure you want to proceed?

## Disabling
![capture0000](https://user-images.githubusercontent.com/24902256/33970774-c20061ca-e029-11e7-9f23-1050b7d9d50a.PNG)

Title: Disable Security Features
Body: You are about to disable the remote access security features and DELETE all user accounts. This will make your printer remotely accessible to everyone within your local network. The dashboard and your printer will automatically restart. This will disrupt any active prints.

Are you sure you want to proceed?

**Comment by peries** [comment]
Can we change the text of the errors that this screen reports?
![capture00000](https://user-images.githubusercontent.com/24902256/33971327-bc3fb634-e02c-11e7-820f-6f529ec91707.PNG)

Title: Enter valid username and password
Body: Please properly fill out the username and password forms
Invalid username
Invalid password
Passwords do not match
Button: OK

**Comment by peries** [comment]
@victorevector  let's talk more about this notification when you can

![capture0](https://user-images.githubusercontent.com/24902256/33971503-a2acdb60-e02d-11e7-8e06-32dc045cb61c.PNG)

**Comment by victorevector** [comment]
@peries @mnacinopa @AllenMcAfee @Ximidar 

I am currently adding the SSH enable/disable radio button to `Settings > Access Control`. This made sense to me given that the option is originally bundled with Access Control in the Security Setup Wizard. The only caveat is that you can only see `Settings > Access Control` if you've enabled Access Control. What are your thoughts?

Pros:
+ Added security layer in front of SSH. You must be logged in with an admin account to enable/disable SSH

Cons:
- The default state (disabled) cannot be changed unless you run the Security Setup Wizard OR you enable Access Control

**Comment by Ximidar** [comment]
I believe they should only see the SSH option when they have access control enabled. having that option hidden behind a login would be nice.

**Comment by mnacinopa** [comment]
Will the Security Setup Wizard run automatically once someone navigates to the web dash after we push the update? The only way i can see this being a problem is for users who actually use SSH, and get blindsided.

**Comment by victorevector** [comment]
@mnacinopa The user will have to enable the Security Setup Wizard from `System` menu drop down

**Comment by mnacinopa** [comment]
@victorevector Okay thats fine. Once we push the update, will SSH just automatically be disabled for all users?

**Comment by victorevector** [comment]
@mnacinopa Per Allen's request yes

**Comment by victorevector** [comment]
@peries @mnacinopa @AllenMcAfee @Ximidar
I won't be able to add the SSH enable/disable button the Settings today. I've tried for a couple hours now and I don't have the proper environment to test it out.  I'll have something ready once I'm back in the office next week.

**Comment by peries** [comment]
@victorevector 

1. Access control screen in the wizard, there's a couple typos
* Since we didn't explain the QR code and mobile app, can you change the first paragraph to

When Access Control is enabled, **you cannot control the printer from the web dashboard unless you are logged in.** Additionally, you can only access the API QR code from the logged in view of the web dashboard. This prevents unregistered users from accessing and using your printer via the internet or mobile app. We advise enabling Access Control when your printer is connected to an unsecure or shared network (such as a school or public places).

* Can you change the note to say

**NOTE:** If you lose your new password, you will need to contact Robo customer support. In which case, you risk losing all of the data on your printer.



2. When access control is enabled, the text for the button to disable it is gone
![capture](https://user-images.githubusercontent.com/24902256/34278423-88180f12-e65f-11e7-96f1-5f7e6ac08dc4.PNG)

3. The password to SSH is raspberry. Is this gonna change?

4. for the notification
![capture0](https://user-images.githubusercontent.com/24902256/34279692-400fd4a4-e667-11e7-802d-967cd72835f8.PNG)
* we need to link that top line to the article that explains access control. https://help.robo3d.com/hc/en-us/articles/115002840791
* How to activate? Go to Settings, then 'Enable remote access security feature' to launch the setup wizard.
* What's inside this feature? Restrict control of the printer via internet access (web dashboard, mobile app, SSH)

**Comment by AllenMcAfee** [comment]
@peries can we go ahead and make the link that is needed in the announcement window?  I'll need to get that into this fix.

**Comment by peries** [comment]
@mnacinopa let us know when the article is updated

**Comment by peries** [comment]
@AllenMcAfee https://help.robo3d.com/hc/en-us/articles/115002840791

**Comment by peries** [comment]
Couple more things where the text is highlighted:
![ac1](https://user-images.githubusercontent.com/24902256/34686747-64e6b182-f461-11e7-9cf5-ad0ec2a13f04.PNG)
should say 'or the Robo mobile app'

![ac2](https://user-images.githubusercontent.com/24902256/34686751-671c8c24-f461-11e7-89dc-1a5cf97995de.PNG)
should say 'password is 'raspberry''

**Comment by Ximidar** [comment]
@peries I fixed those two edits. Could you pull and test?

**Comment by peries** [comment]
Thanks Matt! Looks like everything has been resolved
