### ISSUE TITLE
[Bug] re-enabling access control after disabling it results in a two step wizard

### ISSUE THREAD

**Issue by Ximidar** [Robo3D/roboOctoprint#16]
![screenshot from 2017-12-07 14-49-03](https://user-images.githubusercontent.com/12725744/33742599-fa6a5410-db5d-11e7-9cbb-a73b6c12f239.png)
![screenshot from 2017-12-07 14-49-10](https://user-images.githubusercontent.com/12725744/33742598-f899a708-db5d-11e7-8895-65536e4b9cfe.png)

When I disabled access control I deleted the `salt` entry under Access control, then added the `enabled` entry with a false value. then restarted octoprint. Everything went back to normal

When I re-enabled access controls I set the `enabled` tag to true, then set the `first start` tag to true. Then I restarted octoprint and the wizard looks like this.

**Comment by Ximidar** [comment]
Then after I hit finish, it logs me in as Ximidar, but only because it remembers me. In incognito, it says user unkown.

### Normal Chrome
![screenshot from 2017-12-07 15-03-43](https://user-images.githubusercontent.com/12725744/33743103-2eb5ed90-db60-11e7-856a-4d84e10a983b.png)
### Incognito mode
![screenshot from 2017-12-07 15-03-33](https://user-images.githubusercontent.com/12725744/33743095-2b055e24-db60-11e7-8374-8463d65c7ede.png)

**Comment by victorevector** [comment]
We already discussed this in person, but I'm documenting our discussion here...

This occurs because you disabled Access Control but didn't reset it. You must delete `/home/pi/.octprint/users.yaml` to remove any previous history and reset the wizard. Otherwise, octoprint still thinks there is a user.
