### ISSUE TITLE
1.3.6 delete 'default printer profile' from access control

### ISSUE THREAD

**Issue by peries** [Robo3D/roboOctoprint#29]
since this is a security wizard, the printer profile confirmation does not belong in this setup. the parameters should be able to be autodetected to that the user does not have to go through these screens. plus all the different parameters could be confusing to the user. when octoprint was updated to 1.3.6 this was added as a third step in the wizard.

<img width="1004" alt="screen shot 2018-04-09 at 12 06 17 pm" src="https://user-images.githubusercontent.com/24902256/38760080-29ebeeea-3f2e-11e8-9a8c-4b2feb225675.png">
<img width="1001" alt="screen shot 2018-04-09 at 12 03 31 pm" src="https://user-images.githubusercontent.com/24902256/38760081-2a061c66-3f2e-11e8-9d58-dbfa1ff154f3.png">
<img width="1024" alt="screen shot 2018-04-09 at 12 04 01 pm" src="https://user-images.githubusercontent.com/24902256/38760082-2a206dd2-3f2e-11e8-8645-f12bee508027.png">
<img width="1011" alt="screen shot 2018-04-09 at 12 05 59 pm" src="https://user-images.githubusercontent.com/24902256/38760083-2a3cdb0c-3f2e-11e8-99c3-891e01ff3f70.png">

 

we could look at adding this into the settings page instead

**Comment by peries** [comment]
also is 'lower left' the appropriate origin? the other option was center

**Comment by Ximidar** [comment]
This will not show up anymore
