### ISSUE TITLE
1.3.6 Access control - fix enable/disable buttons

### ISSUE THREAD

**Issue by peries** [Robo3D/roboOctoprint#30]
Once you click one, they both grey out and you cannot change your selection. This happens on the access control and ssh control screens
<img width="1017" alt="screen shot 2018-04-09 at 12 01 40 pm" src="https://user-images.githubusercontent.com/24902256/38758802-8fc24b80-3f27-11e8-8152-fc1ee0506228.png">
<img width="1023" alt="screen shot 2018-04-09 at 12 02 37 pm" src="https://user-images.githubusercontent.com/24902256/38758825-a7cbec72-3f27-11e8-8e41-fe9233953198.png">

**Comment by Ximidar** [comment]
This is by design. The backend will log the user in or disable access control once you have made your choice.
